name: Test and Build

on:
  pull_request:

permissions:
  actions: read
  contents: read

env:
  HUSKY: 0

jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    strategy:
      matrix:
        node-version: [ 20.x ]
        npm-version: [ 10.x ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Get SHAs for for `nx affected` commands
        uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: master

      - name: Set node/npm versions using volta
        uses: volta-cli/action@v4
        with:
          node-version: '${{ matrix.node-version }}'
          npm-version: '${{ matrix.npm-version }}'

      - name: Use the node_modules cache if available
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ steps.versions.outputs.node_version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ steps.versions.outputs.node_version }}-

      - name: Install dependencies
        run: npm ci --include=optional

      - name: Run checks
        run: npx nx format:check
      - name: Build
        run: npx nx affected --target build --parallel 3
      - name: Lint
        run: npx nx affected --target lint --parallel 3
      - name: Test
        run: npx nx affected --target test --parallel 3 --ci --code-coverage
